# Generated by Django 2.2.6 on 2020-10-14 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201013_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(['jpg,', 'png'])]),
        ),
    ]
